f = open('pipelines/feature_pipeline.yaml', 'r')
c = f.read()
f.close()
c = c.replace('split_dataset@3', 'split_dataset@latest')
c = c.replace('normalize_text@2', 'normalize_text@latest')
c = c.replace('length_features@3', 'length_features@latest')
c = c.replace('sentiment_features@3', 'sentiment_features@latest')
c = c.replace('tfidf_features@5', 'tfidf_features@latest')
c = c.replace('sbert_embeddings@2', 'sbert_embeddings@latest')
c = c.replace('merge_features@3', 'merge_features@latest')
f = open('pipelines/feature_pipeline.yaml', 'w')
f.write(c)
f.close()
print('done')