f = open('jobs/train_job.yml', 'r')
c = f.read()
f.close()
c = c.replace('azureml:amazon_review_merged_features_train@latest', 'azureml://datastores/workspaceblobstore/paths/azureml/190c5ce8-380c-46c5-8427-02dd07c4e04e/out/')
c = c.replace('azureml:amazon_review_merged_features_val@latest', 'azureml://datastores/workspaceblobstore/paths/azureml/947dfede-cead-4e44-a0b0-ad81e61ce5d7/out/')
c = c.replace('azureml:amazon_review_merged_features_test@latest', 'azureml://datastores/workspaceblobstore/paths/azureml/a05a2d3b-2540-42a2-8c3f-c150ac7606b7/out/')
f = open('jobs/train_job.yml', 'w')
f.write(c)
f.close()
print('done')