f = open('pipelines/feature_pipeline.yaml', 'r')
c = f.read()
f.close()
c = c.replace('normalize_text@latest', 'normalize_text@2')
c = c.replace('length_features@latest', 'length_features@3')
c = c.replace('sentiment_features@latest', 'sentiment_features@3')
c = c.replace('tfidf_features@latest', 'tfidf_features@5')
c = c.replace('sbert_embeddings@latest', 'sbert_embeddings@2')
c = c.replace('merge_features@latest', 'merge_features@3')
c = c.replace('split_dataset@latest', 'split_dataset@3')
f = open('pipelines/feature_pipeline.yaml', 'w')
f.write(c)
f.close()
print('done')