$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute: azureml:lab4-cluster

inputs:
  sampled_data:
    type: uri_folder
    path: azureml:amazon_electronics_features_v1_sampled_ds@latest

jobs:
  split:
    type: command
    component: azureml:split_dataset:2
    inputs:
      data: ${{parent.inputs.sampled_data}}

  normalize_train:
    type: command
    component: azureml:normalize_text:2
    inputs:
      data: ${{parent.jobs.split.outputs.train}}

  normalize_val:
    type: command
    component: azureml:normalize_text:2
    inputs:
      data: ${{parent.jobs.split.outputs.val}}

  normalize_test:
    type: command
    component: azureml:normalize_text:2
    inputs:
      data: ${{parent.jobs.split.outputs.test}}

  length_train:
    type: command
    component: azureml:length_features:2
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  sentiment_train:
    type: command
    component: azureml:sentiment_features:2
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  tfidf:
    type: command
    component: azureml:tfidf_features:5
    inputs:
      train: ${{parent.jobs.normalize_train.outputs.out}}
      val: ${{parent.jobs.normalize_val.outputs.out}}
      test: ${{parent.jobs.normalize_test.outputs.out}}
      max_features: 500

  sbert_train:
    type: command
    component: azureml:sbert_embeddings:2
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  merge_all:
    type: command
    compute: azureml:mergeOnlyCompute
    component: azureml:merge_features:3
    inputs:
      length: ${{parent.jobs.length_train.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_train.outputs.out}}
      tfidf: ${{parent.jobs.tfidf.outputs.train_out}}
      sbert: ${{parent.jobs.sbert_train.outputs.out}}
